/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Positions */
        get: operations["get_positions_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One Position */
        get: operations["get_one_position_positions__stream_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Universe */
        get: operations["get_universe_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lenses/bands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bands */
        get: operations["get_bands_lenses_bands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lenses/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lens Scores */
        get: operations["get_lens_scores_lenses__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lenses/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lens History */
        get: operations["get_lens_history_lenses__ticker__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lenses/sectors/{sector}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sector Lenses
         * @description Median lens readings for a whole sector on a date.
         */
        get: operations["get_sector_lenses_lenses_sectors__sector__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append Event */
        post: operations["append_event_dev_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/streams/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stream */
        get: operations["get_stream_dev_streams__stream_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/projections/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Projections */
        post: operations["rebuild_projections_dev_projections_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/ingest/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budget */
        get: operations["get_budget_dev_ingest_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/ingest/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Securities */
        post: operations["ingest_securities_dev_ingest_securities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/ingest/prices/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Prices */
        post: operations["ingest_prices_dev_ingest_prices__ticker__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/ingest/dividends/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Dividends */
        post: operations["ingest_dividends_dev_ingest_dividends__ticker__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/ingest/fundamentals/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Fundamentals */
        post: operations["ingest_fundamentals_dev_ingest_fundamentals__ticker__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppendEventRequest */
        AppendEventRequest: {
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /**
             * Stream Type
             * @enum {string}
             */
            stream_type: "position" | "thesis" | "rule" | "research";
            /** Event Type */
            event_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Actor
             * @enum {string}
             */
            actor: "roger" | "ig-api" | "rules-engine";
            /** Expected Seq */
            expected_seq?: number | null;
        };
        /** BandOut */
        BandOut: {
            /** Lens */
            lens: string;
            /** Metric */
            metric: string;
            /** Higher Is Better */
            higher_is_better: boolean;
            /** Description */
            description: string;
            /** Ev Or Ebitda Derived */
            ev_or_ebitda_derived: boolean;
            /** Scored */
            scored: boolean;
            /** Breakpoints */
            breakpoints: [
                number,
                number
            ][];
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /** Stream Type */
            stream_type: string;
            /** Seq */
            seq: number;
            /** Event Type */
            event_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Actor */
            actor: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRunOut */
        JobRunOut: {
            /** Job */
            job: string;
            /** Run Date */
            run_date: unknown;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Calls Used */
            calls_used: number;
            /** Tickers Updated */
            tickers_updated: number;
            /** Tickers Failed */
            tickers_failed: number;
            /** Scores Written */
            scores_written: number;
            /** Failures */
            failures: {
                [key: string]: unknown;
            } | null;
            /** Notes */
            notes: string | null;
            /** Stalled */
            stalled: boolean;
        };
        /** LensCell */
        LensCell: {
            /** Score */
            score: number | null;
            /** Score Absolute */
            score_absolute: number | null;
            /** Coverage */
            coverage: number;
            /** Applicable */
            applicable: boolean;
        };
        /** LensHistoryPointOut */
        LensHistoryPointOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Score */
            score: number | null;
            /** Score Absolute */
            score_absolute: number | null;
            /** Coverage */
            coverage: number;
            /** Applicable */
            applicable: boolean;
        };
        /** LensScoreOut */
        LensScoreOut: {
            /** Lens */
            lens: string;
            /** Score */
            score: number | null;
            /** Score Absolute */
            score_absolute: number | null;
            /** Relative Premium */
            relative_premium: number | null;
            /** Coverage */
            coverage: number;
            /** Applicable */
            applicable: boolean;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
        };
        /** LensScoresOut */
        LensScoresOut: {
            /** Ticker */
            ticker: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Scoring Version */
            scoring_version: string;
            /** Dispersion */
            dispersion: number | null;
            /** Stored */
            stored: boolean;
            /** Dispersion Stored */
            dispersion_stored: boolean;
            /** Computed At */
            computed_at: string | null;
            /** Stale Days */
            stale_days: number | null;
            /** Scores */
            scores: components["schemas"]["LensScoreOut"][];
        };
        /** PositionOut */
        PositionOut: {
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /** Instrument Type */
            instrument_type: string;
            /** Ticker */
            ticker: string;
            /** Direction */
            direction: string;
            /** Size */
            size: string;
            /** Entry Price */
            entry_price: string;
            /** Current Stop */
            current_stop: string | null;
            /** Initial Risk */
            initial_risk: string | null;
            /** Current Risk */
            current_risk: string | null;
            /** Currency */
            currency: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Status */
            status: string;
            /** Last Event Id */
            last_event_id: number;
        };
        /** SectorLensOut */
        SectorLensOut: {
            /** Sector */
            sector: string;
            /** Lens */
            lens: string;
            /** Median Score */
            median_score: number | null;
            /** Median Score Absolute */
            median_score_absolute: number | null;
            /** Median Relative Premium */
            median_relative_premium: number | null;
            /** Member Count */
            member_count: number;
        };
        /** UniverseOut */
        UniverseOut: {
            /** As Of */
            as_of: string | null;
            /** Scoring Version */
            scoring_version: string;
            /** Computed At */
            computed_at: string | null;
            /** Stale Days */
            stale_days: number | null;
            /** Count */
            count: number;
            /** Rows */
            rows: components["schemas"]["UniverseRow"][];
        };
        /** UniverseRow */
        UniverseRow: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string;
            /** Subsector */
            subsector: string | null;
            /** Size */
            size: string;
            /** Currency */
            currency: string | null;
            /** Quote Currency */
            quote_currency: string | null;
            /** Market Cap */
            market_cap: number | null;
            /** Dispersion */
            dispersion: number | null;
            /** Usable Lenses */
            usable_lenses: number | null;
            /** Lenses */
            lenses: {
                [key: string]: components["schemas"]["LensCell"];
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_positions_positions_get: {
        parameters: {
            query?: {
                status?: ("open" | "closed") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one_position_positions__stream_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_universe_universe_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bands_lenses_bands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BandOut"][];
                };
            };
        };
    };
    get_lens_scores_lenses__ticker__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LensScoresOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lens_history_lenses__ticker__history_get: {
        parameters: {
            query: {
                lens: string;
                from: string;
                to: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LensHistoryPointOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sector_lenses_lenses_sectors__sector__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                sector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorLensOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_jobs_get: {
        parameters: {
            query?: {
                job?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_event_dev_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stream_dev_streams__stream_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_projections_dev_projections_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    get_budget_dev_ingest_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ingest_securities_dev_ingest_securities_post: {
        parameters: {
            query?: {
                /** @description Show what would be fetched, spend nothing */
                dry_run?: boolean;
                force?: boolean;
                tickers?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_prices_dev_ingest_prices__ticker__post: {
        parameters: {
            query?: {
                /** @description Show what would be fetched, spend nothing */
                dry_run?: boolean;
                force?: boolean;
                from?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_dividends_dev_ingest_dividends__ticker__post: {
        parameters: {
            query?: {
                /** @description Show what would be fetched, spend nothing */
                dry_run?: boolean;
                force?: boolean;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_fundamentals_dev_ingest_fundamentals__ticker__post: {
        parameters: {
            query?: {
                /** @description Show what would be fetched, spend nothing */
                dry_run?: boolean;
                force?: boolean;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
