/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Positions */
        get: operations["get_positions_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One Position */
        get: operations["get_one_position_positions__stream_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Universe */
        get: operations["get_universe_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universe Health */
        get: operations["universe_health_universe_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Securities
         * @description Look a company up by name or partial symbol before adding it.
         */
        get: operations["search_securities_universe_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Securities
         * @description Ingest new tickers: metadata, prices, fundamentals, then score them.
         *
         *     Deliberately synchronous and slow — a first ingest is a few seconds per
         *     ticker — so the UI can report real progress rather than pretending.
         */
        post: operations["add_securities_universe_securities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe/securities/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Security
         * @description Soft delete. History and any events referencing it survive untouched.
         */
        delete: operations["remove_security_universe_securities__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/company/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_company__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/company/{ticker}/peers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Peers
         * @description Sector peers compared on one lens's metrics only.
         *
         *     Deliberately scoped to a single lens: a table of every metric for every
         *     peer is a spreadsheet, not a comparison.
         */
        get: operations["get_peers_company__ticker__peers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/company/{ticker}/metric-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metric History
         * @description Derived metrics recomputed at each historical reporting period.
         *
         *     Ratios are not stored — they are formed at scoring time from raw line
         *     items — so a history is built by replaying the derivation over each
         *     period's trailing window. Slower than reading a stored series, but it can
         *     never disagree with the live score, and a formula change is reflected
         *     immediately without a backfill.
         */
        get: operations["get_metric_history_company__ticker__metric_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screener/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved */
        get: operations["list_saved_screener_saved_get"];
        put?: never;
        /** Save Screen */
        post: operations["save_screen_screener_saved_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screener/saved/{screen_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Saved */
        delete: operations["delete_saved_screener_saved__screen_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_watchlist_get"];
        put?: never;
        /** Add To Watchlist */
        post: operations["add_to_watchlist_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_watchlist__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Points */
        get: operations["list_points_research_points_get"];
        put?: never;
        /** Create Point */
        post: operations["create_point_research_points_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/points/{point_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Point */
        delete: operations["delete_point_research_points__point_id__delete"];
        options?: never;
        head?: never;
        /** Update Point */
        patch: operations["update_point_research_points__point_id__patch"];
        trace?: never;
    };
    "/research/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clips */
        get: operations["list_clips_research_clips_get"];
        put?: never;
        /** Create Clip */
        post: operations["create_clip_research_clips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/clips/{clip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Clip */
        delete: operations["delete_clip_research_clips__clip_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sector Aggregates
         * @description Sector lens medians — the evidence a sector case is argued against.
         */
        get: operations["sector_aggregates_research_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_book_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/book/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Trade
         * @description The first real write path to the event store from the UI.
         */
        post: operations["record_trade_book_trades_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decisions */
        get: operations["list_decisions_decisions_get"];
        put?: never;
        /** Raise Decision */
        post: operations["raise_decision_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions/{stream_id}/take": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take Decision */
        post: operations["take_decision_decisions__stream_id__take_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions/{stream_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline Decision */
        post: operations["decline_decision_decisions__stream_id__decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions/{stream_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Decision */
        post: operations["close_decision_decisions__stream_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions/{stream_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Decision Audit
         * @description Raw event stream. occurred_at and recorded_at both shown: when it
         *     happened and when we were told are different facts.
         */
        get: operations["decision_audit_decisions__stream_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Assistant Available
         * @description Whether Ask Claude can work, so the UI can explain its absence.
         */
        get: operations["assistant_available_assistant_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_assistant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lenses/bands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bands */
        get: operations["get_bands_lenses_bands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lenses/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lens Scores */
        get: operations["get_lens_scores_lenses__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lenses/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lens History */
        get: operations["get_lens_history_lenses__ticker__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lenses/sectors/{sector}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sector Lenses
         * @description Median lens readings for a whole sector on a date.
         */
        get: operations["get_sector_lenses_lenses_sectors__sector__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/earnings/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Earnings */
        get: operations["get_earnings_earnings__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest/pre-earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Pre Earnings */
        post: operations["post_pre_earnings_backtest_pre_earnings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest/pre-earnings/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Sweep */
        post: operations["post_sweep_backtest_pre_earnings_sweep_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_backtest_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_backtest_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest/pre-earnings/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Segments
         * @description Sector, size and froth breakdowns, each against its own drift control.
         *
         *     Slow: one full backtest plus a bootstrap per segment. The multiple-
         *     comparison correction is computed across every segment in the response,
         *     so calling this and reading one row is not the same as testing one thing.
         */
        post: operations["post_segments_backtest_pre_earnings_segments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append Event */
        post: operations["append_event_dev_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/streams/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stream */
        get: operations["get_stream_dev_streams__stream_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/projections/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Projections */
        post: operations["rebuild_projections_dev_projections_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/ingest/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budget */
        get: operations["get_budget_dev_ingest_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/ingest/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Securities */
        post: operations["ingest_securities_dev_ingest_securities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/ingest/prices/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Prices */
        post: operations["ingest_prices_dev_ingest_prices__ticker__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/ingest/dividends/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Dividends */
        post: operations["ingest_dividends_dev_ingest_dividends__ticker__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/ingest/fundamentals/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Fundamentals */
        post: operations["ingest_fundamentals_dev_ingest_fundamentals__ticker__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddSecurityIn */
        AddSecurityIn: {
            /** Tickers */
            tickers: string[];
        };
        /** AppendEventRequest */
        AppendEventRequest: {
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /**
             * Stream Type
             * @enum {string}
             */
            stream_type: "position" | "thesis" | "rule" | "research";
            /** Event Type */
            event_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Actor
             * @enum {string}
             */
            actor: "roger" | "ig-api" | "rules-engine";
            /** Expected Seq */
            expected_seq?: number | null;
        };
        /** AssistantMessage */
        AssistantMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** AssistantReply */
        AssistantReply: {
            /** Reply */
            reply: string;
            /** Model */
            model: string;
            /**
             * Refused
             * @default false
             */
            refused: boolean;
        };
        /** AssistantRequest */
        AssistantRequest: {
            /** Messages */
            messages: components["schemas"]["AssistantMessage"][];
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /** BandOut */
        BandOut: {
            /** Lens */
            lens: string;
            /** Metric */
            metric: string;
            /** Higher Is Better */
            higher_is_better: boolean;
            /** Description */
            description: string;
            /** Ev Or Ebitda Derived */
            ev_or_ebitda_derived: boolean;
            /** Scored */
            scored: boolean;
            /** Breakpoints */
            breakpoints: [
                number,
                number
            ][];
        };
        /** BookOut */
        BookOut: {
            /** Positions */
            positions: components["schemas"]["app__screens_router__PositionOut"][];
            /** Committed Capital */
            committed_capital: number | null;
            /** Total Notional */
            total_notional: number;
            /** Total Risk */
            total_risk: number;
            /** Clusters */
            clusters: {
                [key: string]: unknown;
            }[];
        };
        /** ClipIn */
        ClipIn: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Url */
            url?: string | null;
            /** Summary */
            summary?: string | null;
            /** Tickers */
            tickers?: string[];
        };
        /** ClipOut */
        ClipOut: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Url */
            url?: string | null;
            /** Summary */
            summary?: string | null;
            /** Tickers */
            tickers?: string[];
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CompanyOut */
        CompanyOut: {
            /** Stored */
            stored: boolean;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string;
            /** Subsector */
            subsector: string | null;
            /** Exchange */
            exchange: string | null;
            /** Currency */
            currency: string | null;
            /** Quote Currency */
            quote_currency: string | null;
            /** Market Cap */
            market_cap: number | null;
            /** Is Active */
            is_active: boolean;
            /** As Of */
            as_of: string | null;
            /** Scoring Version */
            scoring_version: string;
            /** Dispersion */
            dispersion: number | null;
            /** Usable Lenses */
            usable_lenses: number | null;
            /** Highest Lens */
            highest_lens: string | null;
            /** Lowest Lens */
            lowest_lens: string | null;
            /** Lenses */
            lenses: components["schemas"]["LensDetail"][];
        };
        /** DecisionCloseIn */
        DecisionCloseIn: {
            /**
             * Decision Quality
             * @enum {string}
             */
            decision_quality: "good" | "bad";
            /**
             * Outcome Quality
             * @enum {string}
             */
            outcome_quality: "good" | "bad" | "neutral";
            /**
             * Error Tag
             * @enum {string}
             */
            error_tag: "analytical" | "informational" | "behavioural" | "sizing" | "timing" | "none";
            /** Note */
            note?: string | null;
        };
        /** DecisionIn */
        DecisionIn: {
            /** Ticker */
            ticker?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "buy" | "sell" | "trim" | "add" | "hold";
            /** Thesis */
            thesis: string;
            /** Premortem */
            premortem: string;
            /** Falsifier */
            falsifier: string;
            /** Sizing Note */
            sizing_note?: string | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /** Ticker */
            ticker: string | null;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Thesis */
            thesis: string;
            /** Premortem */
            premortem: string;
            /** Falsifier */
            falsifier: string;
            /** Sizing Note */
            sizing_note: string | null;
            /** Declined Reason */
            declined_reason: string | null;
            /** Decision Quality */
            decision_quality: string | null;
            /** Outcome Quality */
            outcome_quality: string | null;
            /** Error Tag */
            error_tag: string | null;
            /** Close Note */
            close_note: string | null;
            /**
             * Raised At
             * Format: date-time
             */
            raised_at: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Closed At */
            closed_at: string | null;
        };
        /** EarningsOut */
        EarningsOut: {
            /** Ticker */
            ticker: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Next Report Date */
            next_report_date: string | null;
            /** Next Is Estimated */
            next_is_estimated: boolean | null;
            /** Days To Earnings */
            days_to_earnings: number | null;
            /** History */
            history: components["schemas"]["EarningsRow"][];
        };
        /** EarningsRow */
        EarningsRow: {
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Report Date */
            report_date: string | null;
            /** Is Estimated */
            is_estimated: boolean;
            /** Before After Market */
            before_after_market: string | null;
            /** Eps Estimate */
            eps_estimate: number | null;
            /** Eps Actual */
            eps_actual: number | null;
            /** Surprise Percent */
            surprise_percent: number | null;
            /**
             * Observed On
             * Format: date
             */
            observed_on: string;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /** Stream Type */
            stream_type: string;
            /** Seq */
            seq: number;
            /** Event Type */
            event_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Actor */
            actor: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRunOut */
        JobRunOut: {
            /** Job */
            job: string;
            /** Run Date */
            run_date: unknown;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Calls Used */
            calls_used: number;
            /** Tickers Updated */
            tickers_updated: number;
            /** Tickers Failed */
            tickers_failed: number;
            /** Scores Written */
            scores_written: number;
            /** Failures */
            failures: {
                [key: string]: unknown;
            } | null;
            /** Notes */
            notes: string | null;
            /** Stalled */
            stalled: boolean;
        };
        /** LensCell */
        LensCell: {
            /** Score */
            score: number | null;
            /** Score Absolute */
            score_absolute: number | null;
            /** Coverage */
            coverage: number;
            /** Applicable */
            applicable: boolean;
        };
        /** LensDetail */
        LensDetail: {
            /** Lens */
            lens: string;
            /** Score */
            score: number | null;
            /** Score Absolute */
            score_absolute: number | null;
            /** Relative Premium */
            relative_premium: number | null;
            /** Sector Median */
            sector_median: number | null;
            /** Sector Median Absolute */
            sector_median_absolute: number | null;
            /** Coverage */
            coverage: number;
            /** Applicable */
            applicable: boolean;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
        };
        /** LensHistoryPointOut */
        LensHistoryPointOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Score */
            score: number | null;
            /** Score Absolute */
            score_absolute: number | null;
            /** Coverage */
            coverage: number;
            /** Applicable */
            applicable: boolean;
        };
        /** LensScoreOut */
        LensScoreOut: {
            /** Lens */
            lens: string;
            /** Score */
            score: number | null;
            /** Score Absolute */
            score_absolute: number | null;
            /** Relative Premium */
            relative_premium: number | null;
            /** Coverage */
            coverage: number;
            /** Applicable */
            applicable: boolean;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
        };
        /** LensScoresOut */
        LensScoresOut: {
            /** Ticker */
            ticker: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Scoring Version */
            scoring_version: string;
            /** Dispersion */
            dispersion: number | null;
            /** Stored */
            stored: boolean;
            /** Dispersion Stored */
            dispersion_stored: boolean;
            /** Computed At */
            computed_at: string | null;
            /** Stale Days */
            stale_days: number | null;
            /** Scores */
            scores: components["schemas"]["LensScoreOut"][];
        };
        /** MetricSeries */
        MetricSeries: {
            /** Metric */
            metric: string;
            /** Points */
            points: [
                string,
                number
            ][];
            /** Unavailable Reason */
            unavailable_reason?: string | null;
            /** Suggested Alternative */
            suggested_alternative?: string | null;
        };
        /** PeerRow */
        PeerRow: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Is Self */
            is_self: boolean;
            /** Score */
            score: number | null;
            /** Score Absolute */
            score_absolute: number | null;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
        /** PointIn */
        PointIn: {
            /**
             * Scope Type
             * @enum {string}
             */
            scope_type: "sector" | "ticker";
            /** Scope Value */
            scope_value: string;
            /**
             * Stance
             * @enum {string}
             */
            stance: "for" | "against";
            /** Body */
            body: string;
            /** Source Title */
            source_title?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
        };
        /** PointOut */
        PointOut: {
            /**
             * Scope Type
             * @enum {string}
             */
            scope_type: "sector" | "ticker";
            /** Scope Value */
            scope_value: string;
            /**
             * Stance
             * @enum {string}
             */
            stance: "for" | "against";
            /** Body */
            body: string;
            /** Source Title */
            source_title?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /** Id */
            id: number;
            /** Stress Test */
            stress_test?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PointPatch */
        PointPatch: {
            /** Body */
            body?: string | null;
            /** Pinned */
            pinned?: boolean | null;
            /** Source Title */
            source_title?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Stress Test */
            stress_test?: string | null;
        };
        /** PreEarningsRequest */
        PreEarningsRequest: {
            /**
             * Enter Days Before
             * @default 10
             */
            enter_days_before: number;
            /**
             * Exit Days Before
             * @default 2
             */
            exit_days_before: number;
            /**
             * Start
             * Format: date
             * @default 2010-01-01
             */
            start: string;
            /**
             * End
             * Format: date
             * @default 2026-08-01
             */
            end: string;
            /**
             * Spread Bps
             * @default 10
             */
            spread_bps: number;
            /**
             * Commission Bps
             * @default 5
             */
            commission_bps: number;
            /**
             * Funding Annual Pct
             * @default 0
             */
            funding_annual_pct: number;
            /**
             * Leveraged
             * @default false
             */
            leveraged: boolean;
            /**
             * Variants Tested
             * @default 1
             */
            variants_tested: number;
            /**
             * Persist
             * @default true
             */
            persist: boolean;
        };
        /** SavedScreenIn */
        SavedScreenIn: {
            /** Name */
            name: string;
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
        };
        /** SavedScreenOut */
        SavedScreenOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SectorLensOut */
        SectorLensOut: {
            /** Sector */
            sector: string;
            /** Lens */
            lens: string;
            /** Median Score */
            median_score: number | null;
            /** Median Score Absolute */
            median_score_absolute: number | null;
            /** Median Relative Premium */
            median_relative_premium: number | null;
            /** Member Count */
            member_count: number;
        };
        /** SegmentRequest */
        SegmentRequest: {
            /**
             * Enter Days Before
             * @default 10
             */
            enter_days_before: number;
            /**
             * Exit Days Before
             * @default 2
             */
            exit_days_before: number;
            /**
             * Start
             * Format: date
             * @default 2010-01-01
             */
            start: string;
            /**
             * End
             * Format: date
             * @default 2026-08-01
             */
            end: string;
            /**
             * Spread Bps
             * @default 10
             */
            spread_bps: number;
            /**
             * Commission Bps
             * @default 5
             */
            commission_bps: number;
        };
        /** SweepRequest */
        SweepRequest: {
            /**
             * Enter Days
             * @default [
             *       5,
             *       10,
             *       20
             *     ]
             */
            enter_days: number[];
            /**
             * Exit Days
             * @default [
             *       1,
             *       3
             *     ]
             */
            exit_days: number[];
            /**
             * Start
             * Format: date
             * @default 2010-01-01
             */
            start: string;
            /**
             * End
             * Format: date
             * @default 2026-08-01
             */
            end: string;
            /**
             * Spread Bps
             * @default 10
             */
            spread_bps: number;
            /**
             * Commission Bps
             * @default 5
             */
            commission_bps: number;
        };
        /** TradeIn */
        TradeIn: {
            /** Stream Id */
            stream_id?: string | null;
            /** Instrument */
            instrument: string;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "spreadbet" | "option" | "share";
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Quantity */
            quantity: number;
            /** Price */
            price: number;
            /**
             * Currency
             * @default GBP
             */
            currency: string;
            /** Stop */
            stop?: number | null;
            /** Sleeve */
            sleeve?: ("high_growth" | "deeply_undervalued") | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** UniverseOut */
        UniverseOut: {
            /** As Of */
            as_of: string | null;
            /** Scoring Version */
            scoring_version: string;
            /** Computed At */
            computed_at: string | null;
            /** Stale Days */
            stale_days: number | null;
            /** Count */
            count: number;
            /** Rows */
            rows: components["schemas"]["UniverseRow"][];
        };
        /** UniverseRow */
        UniverseRow: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string;
            /** Subsector */
            subsector: string | null;
            /** Size */
            size: string;
            /** Currency */
            currency: string | null;
            /** Quote Currency */
            quote_currency: string | null;
            /** Market Cap */
            market_cap: number | null;
            /** Dispersion */
            dispersion: number | null;
            /** Usable Lenses */
            usable_lenses: number | null;
            /** Days To Earnings */
            days_to_earnings: number | null;
            /** Lenses */
            lenses: {
                [key: string]: components["schemas"]["LensCell"];
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistIn */
        WatchlistIn: {
            /** Ticker */
            ticker: string;
            /** Note */
            note?: string | null;
        };
        /** WatchlistOut */
        WatchlistOut: {
            /** Ticker */
            ticker: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Note */
            note: string | null;
        };
        /** PositionOut */
        app__projections__router__PositionOut: {
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /** Instrument Type */
            instrument_type: string;
            /** Ticker */
            ticker: string;
            /** Direction */
            direction: string;
            /** Size */
            size: string;
            /** Entry Price */
            entry_price: string;
            /** Current Stop */
            current_stop: string | null;
            /** Initial Risk */
            initial_risk: string | null;
            /** Current Risk */
            current_risk: string | null;
            /** Currency */
            currency: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Status */
            status: string;
            /** Last Event Id */
            last_event_id: number;
        };
        /** PositionOut */
        app__screens_router__PositionOut: {
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string | null;
            /** Sector */
            sector: string | null;
            /** Instrument Type */
            instrument_type: string;
            /** Direction */
            direction: string;
            /** Size */
            size: number;
            /** Entry Price */
            entry_price: number;
            /** Current Stop */
            current_stop: number | null;
            /** Initial Risk */
            initial_risk: number | null;
            /** Current Risk */
            current_risk: number | null;
            /** Currency */
            currency: string;
            /** Sleeve */
            sleeve: string | null;
            /** Status */
            status: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Notional */
            notional: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_positions_positions_get: {
        parameters: {
            query?: {
                status?: ("open" | "closed") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__projections__router__PositionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one_position_positions__stream_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__projections__router__PositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_universe_universe_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    universe_health_universe_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_securities_universe_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_securities_universe_securities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSecurityIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_security_universe_securities__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_company__ticker__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_peers_company__ticker__peers_get: {
        parameters: {
            query: {
                lens: string;
                as_of?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metric_history_company__ticker__metric_history_get: {
        parameters: {
            query: {
                /** @description comma-separated metric names */
                metrics: string;
                range?: "12M" | "5Y" | "MAX";
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSeries"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_screener_saved_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScreenOut"][];
                };
            };
        };
    };
    save_screen_screener_saved_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedScreenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScreenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_saved_screener_saved__screen_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"][];
                };
            };
        };
    };
    add_to_watchlist_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_watchlist__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_points_research_points_get: {
        parameters: {
            query?: {
                scope_type?: string | null;
                scope_value?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_point_research_points_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_point_research_points__point_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                point_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_point_research_points__point_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                point_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clips_research_clips_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_clip_research_clips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClipIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_clip_research_clips__clip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sector_aggregates_research_sectors_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_book_get: {
        parameters: {
            query?: {
                committed_capital?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_trade_book_trades_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"][];
                };
            };
        };
    };
    raise_decision_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_decision_decisions__stream_id__take_post: {
        parameters: {
            query?: {
                note?: string | null;
            };
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_decision_decisions__stream_id__decline_post: {
        parameters: {
            query: {
                reason: string;
            };
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_decision_decisions__stream_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionCloseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_audit_decisions__stream_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_available_assistant_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ask_assistant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantReply"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bands_lenses_bands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BandOut"][];
                };
            };
        };
    };
    get_lens_scores_lenses__ticker__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LensScoresOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lens_history_lenses__ticker__history_get: {
        parameters: {
            query: {
                lens: string;
                from: string;
                to: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LensHistoryPointOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sector_lenses_lenses_sectors__sector__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                sector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorLensOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_jobs_get: {
        parameters: {
            query?: {
                job?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_earnings_earnings__ticker__get: {
        parameters: {
            query?: {
                as_of?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarningsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_pre_earnings_backtest_pre_earnings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreEarningsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_sweep_backtest_pre_earnings_sweep_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SweepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_backtest_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_backtest_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_segments_backtest_pre_earnings_segments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_event_dev_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stream_dev_streams__stream_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_projections_dev_projections_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    get_budget_dev_ingest_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ingest_securities_dev_ingest_securities_post: {
        parameters: {
            query?: {
                /** @description Show what would be fetched, spend nothing */
                dry_run?: boolean;
                force?: boolean;
                tickers?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_prices_dev_ingest_prices__ticker__post: {
        parameters: {
            query?: {
                /** @description Show what would be fetched, spend nothing */
                dry_run?: boolean;
                force?: boolean;
                from?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_dividends_dev_ingest_dividends__ticker__post: {
        parameters: {
            query?: {
                /** @description Show what would be fetched, spend nothing */
                dry_run?: boolean;
                force?: boolean;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_fundamentals_dev_ingest_fundamentals__ticker__post: {
        parameters: {
            query?: {
                /** @description Show what would be fetched, spend nothing */
                dry_run?: boolean;
                force?: boolean;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
